baitap1/Models/ErrorViewModel.cs
namespace baitap1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

baitap1/Models/Model1.cs
namespace baitap1.Models
{
    public class Model1
    {
        public string Property1 { get; set; }
    }
}

baitap1/Models/Model2.cs
namespace baitap1.Models
{
    public class Model2
    {
        public string Property2 { get; set; }
    }
}

baitap1/Controllers/HomeController.cs
using baitap1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace baitap1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

baitap1/Controllers/Project1Controller.cs
using baitap1.Models;
using Microsoft.AspNetCore.Mvc;

namespace baitap1.Controllers
{
    public class Project1Controller : Controller
    {
        public IActionResult Function1()
        {
            var model = new Model1 { Property1 = "Data from Model1" };
            return View(model);
        }

        public IActionResult Function2()
        {
            var model = new Model1 { Property1 = "Data from Model1" };
            return View(model);
        }
    }
}

baitap1/Controllers/Project2Controller.cs
using baitap1.Models;
using Microsoft.AspNetCore.Mvc;

namespace baitap1.Controllers
{
    public class Project2Controller : Controller
    {
        public IActionResult Function1()
        {
            var model = new Model2 { Property2 = "Data from Model2" };
            return View(model);
        }

        public IActionResult Function2()
        {
            var model = new Model2 { Property2 = "Data from Model2" };
            return View(model);
        }
    }
}

baitap1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

baitap1/Views/Project1/Function1.cshtml
<h2>Chức năng 1 - Project 1</h2>
<p>@Model.Property1</p>

baitap1/Views/Project1/Function2.cshtml
<h2>Chức năng 2 - Project 1</h2>
<p>@Model.Property1</p>

baitap1/Views/Project2/Function1.cshtml
<h2>Chức năng 1 - Project 2</h2>
<p>@Model.Property2</p>

baitap1/Views/Project2/Function2.cshtml
<h2>Chức năng 2 - Project 2</h2>
<p>@Model.Property2</p>

baitap1/Views/Shared/_Layout.cshtml
<!-- Views/Shared/_Layout.cshtml -->
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <!-- Các thẻ meta, CSS, JavaScript cần thiết -->
</head>
<body>
    <div id="header">
        <!-- Header của trang -->
    </div>

    <div id="menu">
        <!-- Đặt partial view danh mục menu ở đây -->
        @Html.Partial("_MenuPartial")
    </div>

    <div id="content">
        @RenderBody()
    </div>

    <div id="footer">
        <!-- Footer của trang -->
    </div>
</body>
</html>

baitap1/Views/Shared/_MenuPartial.cshtml
<!-- Views/Shared/_MenuPartial.cshtml -->
<ul>
    <li>@Html.ActionLink("Trang chủ", "Index", "Home")</li>
    <li>@Html.ActionLink("Chức năng 1 - Project 1", "Function1", "Project1")</li>
    <li>@Html.ActionLink("Chức năng 2 - Project 1", "Function2", "Project1")</li>
    <li>@Html.ActionLink("Chức năng 1 - Project 2", "Function1", "Project2")</li>
    <li>@Html.ActionLink("Chức năng 2 - Project 2", "Function2", "Project2")</li>
</ul>